### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sam-gagnon** [Juris-M/citeproc-test-runner#12]
Hello!

I'm reposting this here since it apparently got deleted on the other issue thread I had opened.

Since the update yesterday, anytime I attempt to run a test, I receive this error:

     TypeError: Cannot read property 'length' of undefined
      at preloadAbbreviations (C:\Users\sgagn\AppData\Roaming\npm\node_modules\citeproc-test-runner\lib\preload.js:202:46)
      at Sys.run (C:\Users\sgagn\AppData\Roaming\npm\node_modules\citeproc-test-runner\lib\sys.js:376:13)
      at Context.<anonymous> (C:\Users\sgagn\.cslTestFixtures\fixtures.js:251:27)
      at processImmediate (internal/timers.js:456:21)

I tried running the tests for jm-leg-cit-literaturverzeichnis.csl and for jm-chicago-fullnote-bibliography.csl, to see if it was my style that was causing it, but I get the same error there as well.

Any idea what it is causing it? I tried uninstalling and reinstalling citeproc-test-runner, but no dice. If you need any more info to help figure this out, please let me know.

**Comment by sam-gagnon** [comment]
This was solved in the newest update.
