### ISSUE TITLE
Tests stopped working

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-test-runner#13]
Running the tests on jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis.csl I get this error after six successful tests:

```
1) Integration tests
       Test no-repeat court name atCaseNoRepeat_test015:
     TypeError: Cannot read property 'id' of undefined
      at preloadAbbreviations (/usr/local/lib/node_modules/citeproc-test-runner/lib/preload.js:203:44)
      at Sys.run (/usr/local/lib/node_modules/citeproc-test-runner/lib/sys.js:381:13)
      at Context.<anonymous> (.cslTestFixtures/fixtures.js:2448:27)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by fbennett** [comment]
Sorry about that. Code is fixed now.

**Comment by georgd** [comment]
Cool, thanks! Still something wrong here:

```
 1) Integration tests
       undefined bibliography_test999:
     TypeError: Cannot read property 'indexOf' of undefined
      at Object.getAbbrevsDomain (citeproc_commonjs.js:363:55)
      at CSL.Transform.loadAbbreviation (citeproc_commonjs.js:17994:26)
      at CSL.NameOutput.fixupInstitution (citeproc_commonjs.js:14313:49)
      at CSL.NameOutput._renderInstitutionName (citeproc_commonjs.js:13380:24)
      at CSL.NameOutput._renderNames (citeproc_commonjs.js:13626:33)
      at CSL.NameOutput.renderAllNames (citeproc_commonjs.js:13304:37)
      at CSL.NameOutput.outputNames (citeproc_commonjs.js:11979:10)
      at CSL.Token.func (citeproc_commonjs.js:15021:34)
      at CSL.Engine.CSL.tokenExec (citeproc_commonjs.js:2873:26)
      at CSL.Token.func (citeproc_commonjs.js:10607:50)
      at CSL.Engine.CSL.tokenExec (citeproc_commonjs.js:2873:26)
      at CSL.Token.<anonymous> (citeproc_commonjs.js:2948:42)
      at CSL.Engine.CSL.tokenExec (citeproc_commonjs.js:2873:26)
      at CSL.Token.<anonymous> (citeproc_commonjs.js:2948:42)
      at CSL.Engine.CSL.tokenExec (citeproc_commonjs.js:2873:26)
      at CSL.Engine.CSL.getCite (citeproc_commonjs.js:8388:30)
      at CSL.Engine.CSL.getBibliographyEntries (citeproc_commonjs.js:8889:50)
      at CSL.Engine.makeBibliography (citeproc_commonjs.js:8613:38)
      at Sys.run (/usr/local/lib/node_modules/citeproc-test-runner/lib/sys.js:460:38)
      at Context.<anonymous> (.cslTestFixtures/fixtures.js:2448:27)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by fbennett** [comment]
The fixture has a mismatch between the keys set in INPUT and the calls made in CITATION-ITEMS. If CITATION-ITEMS is just removed completely, the test passes.

**Comment by georgd** [comment]
Oh, thanks for spotting that.
