### ISSUE TITLE
CTR crashes with default config

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-test-runner#16]
If I don’t provide a local path to `abbrevs` in cslrun.yml, CTR crashes with this message:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'citeproc-juris-abbrevs'
Require stack:
- /usr/local/lib/node_modules/citeproc-test-runner/lib/configs.js
- /usr/local/lib/node_modules/citeproc-test-runner/runtests.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/citeproc-test-runner/lib/configs.js:134:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/citeproc-test-runner/lib/configs.js',
    '/usr/local/lib/node_modules/citeproc-test-runner/runtests.js'
  ]
}
```

**Comment by fbennett** [comment]
The test runner bundle includes a default copy of the current abbrevs, but that module has being called by the wrong name. README fix merged, and the code should not throw the error now.
