### ISSUE TITLE
Error when updating references

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-test-runner#18]
I’m not sure if you told me already how to fix this but I can’t find it. 

Calling `$ cslrun -w ~/Documents/dev/jm-styles/jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis.csl -U` returns this error:

```
Error: Cannot read property 'versionNumber' of undefined

TypeError: Cannot read property 'versionNumber' of undefined
    at convert (/usr/local/lib/node_modules/citeproc-test-runner/node_modules/zotero2jurismcsl/zotero2jurismCSL.js:92:53)
    at /usr/local/lib/node_modules/citeproc-test-runner/runtests.js:826:31
```

**Comment by fbennett** [comment]
Wading into this now.
